[tool.poetry]
name = "wishes"
version = "0.1.0"
description = ""
authors = ["John Doe <rs16w@github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
poetry = "^1.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
